version: "3.0"
services:
  elasticsearch:
    container_name: es_demo
    hostname: es_demo
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    ports:
      - 9200:9200

  mysql-db:
    container_name: mysql_demo
    image: mysql
    ports:
      - "6033:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456Aa@
      MYSQL_DATABASE: mysql_demo